version: '3'
services:
  op-dashboard:
    build:
      context: ..
      dockerfile: apps/dashboard/Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
        NEXT_PUBLIC_SELF_HOSTED: "true"