version: '3'
services:
  op-dashboard:
    image: op-dashboard-local
    build:
      context: ..
      dockerfile: apps/start/Dockerfile
  
  op-api:
    image: op-api-local
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
  
  op-worker:
    image: op-worker-local
    build:
      context: ..
      dockerfile: apps/worker/Dockerfile
